### ISSUE TITLE
[Feature Request] Changing brightness

### ISSUE THREAD

**Issue by hammad-ilyas-umt** [launchcodedev/pi-camera-connect#11]
Hi, I am using raspberry pi 3b with camera module v1.3. The images are slightly darker than the image I took using raspistill command line tool. Is possible to add support for changing brightness?

**Comment by gregnr** [comment]
Adding this should be fairly simple since `raspistill`/`raspivid` have a `--brightness` option. Feel free to create a PR and we'll be happy to review and merge it in.
