### ISSUE TITLE
Does not recognize BCM2711

### ISSUE THREAD

**Issue by jeffrson** [launchcodedev/pi-camera-connect#12]
The library fails with "Unknown system model 'bcm2711'".

see here for reference 
https://www.raspberrypi.org/documentation/hardware/raspberrypi/bcm2711/README.md

**Comment by gregnr** [comment]
Thanks for bringing this up @jeffrson. We will look into this and follow up.

**Comment by HofmannZ** [comment]
@gregnr Any follow-up? Running into the same issue.

**Comment by HofmannZ** [comment]
@jeffrson for the time being you can use our fork:
```
npm i @zino-hofmann/pi-camera-connect
```

**Comment by gregnr** [comment]
This is available now in release [v0.3.3](/launchcodedev/pi-camera-connect/releases/tag/v0.3.3). Thanks for the PR @HofmannZ.
