### ISSUE TITLE
Running camera example doesnt yeild valid h264

### ISSUE THREAD

**Issue by MartinN3** [launchcodedev/pi-camera-connect#20]
I have used exactly same code as in video capture example.

node v11.9.0 - raspi zero W ARMv6
JT-zero-v2.0 camera

To be exact file outputed is 10MB binnary file. But it can't be read.

Photos works as expected with code provided.

What could be wrong?

**Comment by MartinN3** [comment]
Package raspivid is working - npm install raspivid

Can there be any conclusion drawn from that information?

**Comment by MartinN3** [comment]
MJPEG is working tho..

**Comment by gregnr** [comment]
Hi @MartinN3, thanks for the issue. This library uses the `raspivid` CLI command under the hood just like the [`raspivid` NPM package](https://github.com/binocarlos/raspivid) you referenced does.

That leaves either default configuration or an implementation detail as possible differences between the libraries. It's interesting that you get the 10MB file, but are unable to read it. Also interesting that MJPEG works fine. Can I ask what method you are using to read/play the H.264 file?

**Comment by MartinN3** [comment]
I have came to conclusion that it has to be some argument because code below is working. I will investigate further.

Not working:
// this.childProcess = child_process_1.spawn('raspivid', args); 

Working:
this.childProcess = child_process_1.spawn('raspivid', ['-rot', '270', '-w', '1280', '-h', '720', '-t', '0', '-fps', '5', '-o', '-' , "-n"]);

**Comment by MartinN3** [comment]
It looks like my camera framerate cap was the issue......

Altough its weird that program just produces file and no content without any errors. I will investigate further.

**Comment by MartinN3** [comment]
Looks like awaiting this code (its unused in h264 encoding) cuts first frames of h264 - that results in loosing I-frame initial or NAL    (i dont know right terminology but its missing this: 00 00 00 01 sequence) and file is then unreadable.

const jpegSignature = await StreamCamera.getJpegSignature();

**Comment by alexcherkesov** [comment]
Have the same issue with Zero W. Also found corrupted 00 00 00 01 sequence, and suspect that it is race condition issue, because sometimes it is ok. 
Subscription `this.childProcess.stdout.on('data', (data: Buffer)` should be right after 
`this.childProcess.stdout.once('data', () => resolve());`
and `const jpegSignature = await StreamCamera.getJpegSignature();` could be moved before spawn or even ignored in H264 case.

**Comment by gregnr** [comment]
Thanks for the useful info @MartinN3  and @alexcherkesov, and sorry for the delay. As of [`v0.3.4`](https://github.com/launchcodedev/pi-camera-connect/releases/tag/v0.3.4) we no longer `await` the JPEG signature, so I'm hoping that resolves this issue. Please try it out and let me know if you are still having issues.

**Comment by gregnr** [comment]
@MartinN3 @alexcherkesov  A bit of time has passed now. Did you get a chance to try the latest version?

**Comment by MartinN3** [comment]
Hello, i had chance just last weekend. Video recordings are running fine in updated version. At least i didn't notice any bugs with that anymore.

Thank you!
