### ISSUE TITLE
Options args: iso, exposure, digitalgain...

### ISSUE THREAD

**Issue by jipema** [launchcodedev/pi-camera-connect#8]
Thanks for this awesome tool!
Just one little change would make it even closer to perfection: more options (ISO, exposure, ...), for both StillCamera and StreamCamera.
In my case, I would need to change the --digitalgain in case of low light.

**Comment by gregnr** [comment]
Thanks for the issue @jipema. These are all options I would love to include. Since ISO, exposure, and digital gain can all be configured as arguments to `raspistill`/`raspivid`, these should be fairly easy to implement. Feel free to create a PR and we will be happy to review and merge.

**Comment by darrylhodgins** [comment]
I agree with @jipema; this is an awesome library.

At the risk of making this a laundry list, I think it would be great to accommodate these `raspistill`/`raspivid` options:

* `--shutterspeed`
* `--ev` (EV compensation)
* `--exposure` (exposure mode)
* `--awb` (white balance)
* `--ISO`

There are a few others that would help my usecase (`--roi`, and fine-grained `--width` & `--height`), but I'd argue that's outside the scope of _this_ issue…

**Comment by gregnr** [comment]
This has been added in #14 and released in [v0.3.1](/launchcodedev/pi-camera-connect/releases/tag/v0.3.1). Thanks @darrylhodgins!
